Add doc for load multiple pest files and `include!` syntax.
pest-parser/book pull request #29
Opened 2023-01-09 03:07 UTC by huacnlee

Ref:

- https://github.com/pest-parser/pest/pull/759
- https://github.com/pest-parser/pest/pull/758

2023-01-09 10:08 UTC, CAD97 requested changes
The unrelated changes (probably an ~~overly~~ opinionated format-on-save?) don't belong in this PR, and the ones that touch link anchors are objectively incorrect.

2023-01-09 10:11 UTC, huacnlee commented
It's by Markdown formatter. I have updated.

2023-01-29 01:49 UTC, tomtau approved these changes

2023-01-29 01:49 UTC, tomtau commented on src/grammars/syntax.md
> +
```suggestion
```

2023-01-29 01:49 UTC, tomtau commented on src/grammars/grammars.md
> +This is useful if you have a base grammar that you want to extend in multiple.
```suggestion
This is useful if you have a base grammar that you want to extend in multiple grammars.
```

2023-01-29 01:49 UTC, merged